// import PropTypes from "prop-types"
// import Markdown from "react-markdown"
import React from "react"
import EventCard from "../elements/event/event-card"

const Header = ({ data }) => {
  // let dummyData = [
  //   {
  //     title: "RADx (C)DCC Quarterly Meeting",
  //     timeAndDate: "Thursday, May 26, 2022 2:00-3:00 PM ET",
  //     body: "The RADx Data Hub Partners (DHP) are working together with the RADx Coordination and Data Collection Centers (C)DCCs to create and implement structures that achieve the RADx Data Hub vision - creating a single access point to de-identified COVID-19 RADx and related research data, algorithms, and other capabilities generated by various digital health solutions and technologies for researchers. This quarterly meeting will offer an opportunity for RADx (C)DCCs to share needs, questions, and concerns about data submission timelines and requirements. The RADx DHP will also provide RADx Data Hub updates, an overview of the development timeline, data submission expectations, and key considerations",
  //   },
  // ];
  return (
    <div className="container mt-12">
      <h2 className="mb-[8px] text-[#4a66ac] font-bold text-2xl">
        {data.title}
      </h2>
      <hr className="text-orange border-t-[2px] border-orange"></hr>
      {/* <EventCard data={{}}/> */}

    </div>
  )
}

// Header.propTypes = {
//   data: PropTypes.shape({
//     content: PropTypes.string,
//     border: PropTypes.bool,
//   }),
// }

export default Header
