// import PropTypes from "prop-types"
// import Markdown from "react-markdown"
import React from "react"
import EventCard from "../elements/event/event-card"

const Header = ({ data }) => {
  let dummyData = [
    {
      title: "Ongoing",
      timeAndDate: "",
      body: "The RADx Data Hub Partners hold individual and small-group introduction sessions with early adopters and testers of the RADx Data Hub. To schedule one of these sessions, please contact us.",
      image:
        "https://radx-images.s3.amazonaws.com/Rad_X_Event_14_1_63e4c8a584.png",
    },
    {
      title: "RADx (C)DCC Quarterly Meeting",
      timeAndDate: "Thursday, August 11, 2022 2:00-3:00 PM ET",
      body: "The RADx Data Hub Partners and the RADx Coordination and Data Collection Centers meet quarterly to discuss progress and development milestones key to the RADx Data Hub. testing, regulatory affairs, entrepreneurs, and business leaders.",
      image:
        "https://radx-images.s3.amazonaws.com/Rad_X_Event_14_04ed15964d.png",
    },
  ]
  let dummyData2 = [
    {
      title: "RADx (C)DCC Quarterly Meeting",
      timeAndDate: "Thursday, May 26, 2022 2:00-3:00 PM ET",
      body: "The RADx Data Hub Partners (DHP) are working together with the RADx Coordination and Data Collection Centers (C)DCCs to create and implement structures that achieve the RADx Data Hub vision - creating a single access point to de-identified COVID-19 RADx and related research data, algorithms, and other capabilities generated by various digital health solutions and technologies for researchers. This quarterly meeting will offer an opportunity for RADx (C)DCCs to share needs, questions, and concerns about data submission timelines and requirements. The RADx DHP will also provide RADx Data Hub updates, an overview of the development timeline, data submission expectations, and key considerations",
      image:
        "https://radx-images.s3.amazonaws.com/Rad_X_Event_14_04ed15964d.png",
    },
    {
      title: "RADx (C)DCC Kick-off Meeting",
      timeAndDate: "Thursday, February 17, 2022 2:00-3:00 PM ET",
      body: "The purpose of this meeting is to kick off the RADx Data Hub under the direction of a new team, the RADx Data Hub Partners (RADx DHP), allowing this new team and the RADx (C)DCCs to get to know one another and begin building community. This meeting will include formal introductions of the RADx DHP and RADx program (C)DCCs, a RADx program status update from the NIH perspective, and an overview of RADx DHP visions and goals.",
      image:
        "https://radx-images.s3.amazonaws.com/Rad_X_Event_14_04ed15964d.png",
    },
  ]
  return (
    <div className="container mt-12">
      <h2 className="mb-[8px] text-[#4a66ac] font-bold text-2xl">
        {data.title}
      </h2>
      <hr className="text-orange border-t-[2px] border-orange"></hr>
      {data.title === "Upcoming Events"
        ? dummyData.map((event, i) => {
            return <EventCard key={i + event.title} data={event} />
          })
        : dummyData2.map((event, i) => {
            return <EventCard key={i + event.title} data={event} />
          })}
    </div>
  )
}

// Header.propTypes = {
//   data: PropTypes.shape({
//     content: PropTypes.string,
//     border: PropTypes.bool,
//   }),
// }

export default Header
